-freqMatrix-
-2-
-0.15-
-2-
-False-
-False-
-5-
-,-
cp: cannot stat '/scratch/freqMatrix.*': No such file or directory
cp: cannot stat '/scratch/freqMatrix/freqMatrix.*': No such file or directory
freqMatrix.*
cat: freqMatrix.csv: No such file or directory
freqMatrix.csv converted in markers.txt
cat: freqMatrix_clustering.output.csv: No such file or directory
freqMatrix_clustering.output.csv converted in vis.txt
Error in read.table("vis.txt", header = TRUE, row.names = 1, stringsAsFactors = F) : 
  no lines available in input
Execution halted
Started on 2020-08-25T09:06:01.783415
Set X to 0.15.
Reading data...
Traceback (most recent call last):
  File "/usr/local/bin/Comet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/Comet/__main__.py", line 795, in main
    skipvis=skipvis)
  File "/usr/local/lib/python3.6/dist-packages/Comet/__main__.py", line 98, in read_data
    cls_path, sep='\t', index_col=0, names=['cell', 'cluster'], squeeze=True
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'/scratch/freqMatrix/5/cluster.txt' does not exist
